name: 'Mark issues stale'

on:
  schedule:
    - cron: '20 23 * * *' # Every day at 11:20PM UTC (6:20PM EST)
  workflow_dispatch:

jobs:
  run:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - name: 'Mark issues stale'
        run: node ./.github/actions/next-repo-actions/dist/mark-issue-stale/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
